name: a_village
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk:
    ^3.5.2
    # sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  image_picker: ^0.8.8+1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_card_swiper: ^7.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_dash: ^1.0.0
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Bold.ttf
        - asset: assets/fonts/InterTight-Regular.ttf
